### ISSUE TITLE
Analog read current

### ISSUE THREAD

**Issue by gdlwyverex** [sfera-labs/iono-pi-c-lib#5]
I have an analog current device that I connected to the IONOPi but can find no way in the lib to read the current. It has a voltage read function, but my device modifies current flow to indicate distance. The device is an Ultrasonic M18/M30 diffuse digital and analog output

it should output from 4 - 20mA depending on the distance with an applied voltage of 24vdc.
It is a PNP device which at max distance registers HIGH 

The digital part function fine but I see no way to read the current which would give me the distance

Help please

Richard

**Comment by giampiero7** [comment]
Hi Richard,
Iono Pi does not have a current (4-20mA) analog interface.
You would need to convert the device's current output to a voltage signal and then connect it to Iono's input.
Current inputs are, for instance, available on Iono MKR: https://www.sferalabs.cc/iono-mkr/

I'm going to close this issue since it is not related to this library, if you need other information please, email us at support@sferalabs.cc

Best,
Giampiero
